[package]
name = "essam"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
clap = { version = "4.5.6", features = ["derive"] }
thiserror = "1.0"
crc = "3.2.1"

[profile.release-with-debug]
inherits = "release"
debug = true
